### PR TITLE
added dim_cv attribute to classes staNNet and predNNet

### PR DESCRIPTION
**Pull request by internetvandingen**
Important that this property will still exist after saving and loading.
Would you be so kind to test also?

### CODE REVIEW

**Comment by hcruiz** [comment]
Question: I though you wanted to have a list of the CV indices? Can you explain again, why this change is needed?

**Comment by internetvandingen** [comment]
You explained that the order of indices is always inputs first, then control voltages, thats why I only need the dimension instead of position in the object. (Not talking about the physical gates on the device.)
Right now, dim_cv is used as the number of control voltages but is not saved in the object, the goal of this change is that it saves dim_cvin the object during creation.
In this way, we have all the needed information, because the number of inputs is then D_in-dim_cv.
The object you gave me does have D_in, but not dim_cv, so is this a correct way of going about this?

**Comment by hcruiz** [comment]
Hi Lennart, thanks for reminding me the discussion. I think for now it is fine. I asked because I'm thinking if it isn't smarter to simply treat all inputs equally, now that we are doing changes. When scaling up, we shouldn't have such constrains, so treating them all equal would make everything more transparent. But this requires maybe a bit more discussion with the experimentalists. 
Did you test the code? I don't expect bugs because the changes are minimal, but did you run the code with those changes?
Then I will just accept it.

**Comment by internetvandingen** [comment]
As suggested in #11, these changes will be incorporated in that pull-request as well.

**Pull request closed without merging**
